import { Providers } from "@/lib/state-management/providers";
import { Work_Sans } from "next/font/google";
import "./globals.css";
import ToastComponet from "@/components/notification/ToastComponet";

const workSans = Work_Sans({
  weight: ["500", "600"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${workSans.className} antialiased text-slate-500 bg-white`}
        suppressHydrationWarning={true}
        data-theme="main"
      >
        <Providers>
          <ToastComponet />
          {children}
        </Providers>
      </body>
    </html>
  );
}
